# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KidsWiki' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for KidsWiki



  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'react-native-in-app-utils', :path => '../node_modules/react-native-in-app-utils'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  target 'KidsWikiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


